services:
  proxy:
    image: nginx:latest
    container_name: geekjoke-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    networks:
      - geekjoke-net

  backend:
    image: node:22-alpine
    container_name: geekjoke-backend
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3333
    ports:
      - '3333:3333'
    networks:
      - geekjoke-net
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node ace serve --watch"

  frontend:
    image: node:22-alpine
    container_name: geekjoke-frontend
    working_dir: /app
    ports:
      - '8080:5173' # Vite dev server padr√£o
    networks:
      - geekjoke-net
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:18-alpine
    container_name: geekjoke-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--encoding=UTF8'
    volumes:
      - postgres_data_geekjoke:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    ports:
      - '5432:5432'
    networks:
      - geekjoke-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  geekjoke-net:
    driver: bridge

volumes:
  postgres_data_geekjoke:
